l_russian:
 CONFIGURATOR_TOOLTIP:0 "Настрой себе игру"
 
 nw_configurator_title:0 "§HКонфигуратор мода§!"
 ger_title:0 "Германия:"
 ger_reich:0 "Путь Третьего Рейха"
 ger_kaiser:0 "Путь Кайзера"
 ger_revolt:0 "Путь Револьтрейха"
 ger_democrat:0 "Демократический путь"
 
 hun_title:0 "Венгрия:"
 hun_hbbrg:0 "Восстановить империю Габсбургов"
 hbbrg_fash:0 "Империя Габсбургов: путь Христианской Империи"
 hbbrg_monarch:0 "Империя Габсбургов: путь Австро-Венгрии"
 hbbrg_danubian:0 "Империя Габсбургов: путь Дунайской федерации/СШЕ"
 
 fra_title:0 "Франция:"
 fra_little_entente:0 "Путь "Малой антанты""
 fra_go_with_britain:0 "Пробританский путь"
 fra_support_the_left:0 "Коммунистический путь"
 fra_support_the_right:0 "Фашистский путь"
 fra_support_tro:0 "Марксистский путь"
 
 mex_title:0 "Мексика"
 mex_commi:0 "Коммунистический путь"
 mex_troz:0 "Марксистский путь"
 mex_fash:0 "Фашистский путь"
 mex_dem:0 "Демократический путь"
 
 
 RESET_CONFIGURATOR_TOOLTIP:0 "Сброс приоритетов"
 ENEMY_SWITCH_TOOLTIP:0 "Активация приоритета AI-игроку"
 
 NW_conf_on:0 "£trigger_yes"
 NW_conf_off:0 "£trigger_no"
 
 